### ISSUE TITLE
Parsing issue for  foo?.3

### ISSUE THREAD

**Issue by claudepache** [claudepache/es-optional-chaining#1]
We have to distinguish:

``` js
foo?.3:0  // foo  ?  .3  :  0,  for backward compatibility
foo?.x  // foo  ?.  x
```

For a human the exercise is trivial; the question is whether it may be made reasonably fast and easy for a parser.

In case of negative answer, we should fall back to another syntax, e.g. `.?` or `..`

**Comment by caitp** [comment]
I think you're okay here --- the current grammar is `MemberExpression[?Yield] . IdentifierName`, so a number just doesn't cut it.

**Comment by claudepache** [comment]
> I think you're okay here --- the current grammar is MemberExpression[?Yield] . IdentifierName, so a number just doesn't cut it.

The issue is about the `?` in the newly added `MemberExpression[?Yield] ?. IdentifierName` production, which interferes with the grammar for the conditional operator ([12.13](https://tc39.github.io/ecma262/#sec-conditional-operator)).

**Comment by caitp** [comment]
I can see what the issue is about, but it's just not true --- this doesn't create any ambiguity for ConditionalExpression.

It's one of those cases where you might need backtracking (eg, `MemberExpression ? . <not IdentifierName>` -> backtrack to before the `?`), but I think frontend craziness could avoid the need for backtracking. It would be spec'd as just another cover grammar, probably. CoverMemberExpressionContinuationOrConditionalExpression ?

**Comment by caitp** [comment]
An even less ambiguous way (no cover grammar needed) is to skip `? .` entirely, and just always require `[ ? Expression ]`, which would not even need a cover grammar

**Comment by claudepache** [comment]
> this doesn't create any ambiguity for ConditionalExpression

You're right that there is no ambiguity, but the issue is that discriminating the two cases may complicate lexical analysis. To what extent, I really don’t know, and I'd like to hear practical experience from specialists.

**Comment by caitp** [comment]
"complicate lexical analysis" that ship has sailed for ECMAScript over a year ago, with the introduction of the first cover grammars. I don't think this proposed one is too different (I'm not saying we really want more crazy frontend stuff just for the elvis operator, but if it was a desired feature, this sort of thing has been done before)

**Comment by claudepache** [comment]
> An even less ambiguous way (no cover grammar needed) is to skip ? . entirely, and just always require [ ? Expression ]

I prefer to change the syntax (e.g., using `.?` instead of `?.`) rather than lose the<br> `MemberExpression ?. IdentifierName` form, which I expect to be the most common one.

> It would be spec'd as just another cover grammar, probably. CoverMemberExpressionContinuationOrConditionalExpression ?

I have considered this, but I don’t think that a cover grammar is feasible due to the difference of precedence between the two incriminated operators, as in: `a ?.3 + x : y` vs. `a ?.b + x`.

**Comment by claudepache** [comment]
I've added the following production to the Lexical Grammar:

```
OptionalChainingOperator ::
    ? . [lookahead ∉ DecimalDigit]
```

I.e., the `?.` sequence of characters is interpreted as a token only when it is not followed by a digit. For me, it resolves the issue.
