### ISSUE TITLE
Default operator (aka null-coalescing operator, aka defined-or operator)

### ISSUE THREAD

**Issue by claudepache** [claudepache/es-optional-chaining#10]
There is demand for a default operator (see #9). Currently not included in the proposal, but should be considered.

Syntax: `a ?? b`.

Semantics: Evaluate `a`. If the result is not undefined (and not null?), return  it. Otherwise, evaluate `b` and return the result.

Main open question: Should we use: “undefined”, or: “undefined or null”?
* With just “undefined”, it would match the semantics for defaults in function parameters and destructuring.

**Comment by dogancelik** [comment]
`a ?? b` should work just as `a ? a : b`, if the intention of this operator is to shorten *shorthand if-else* even more.

**Comment by hax** [comment]
@dogancelik `a || b` is same as `a ? a : b`, we don't need new op for that.

**Comment by claudepache** [comment]
Another open question for `??`, is the precedence relatively to other operators, notably `||` (same precedence, lower precedence?)

What do other languages do?

**Comment by claudepache** [comment]
> What do other languages do?

Between `||` and `?  :`

* C#: https://msdn.microsoft.com/en-us/library/6a71f45d.aspx
* PHP: http://php.net/manual/en/language.operators.precedence.php

Same level as `||` :

* Perl6: https://docs.perl6.org/language/operators (the operator is spelled `//`)

Higher precedence than comparison operators:

* Swift: https://developer.apple.com/reference/swift/swift_standard_library_operators

**Comment by hax** [comment]
Because comparison always return boolean (or NaN in some cases), which never null/undefined, so I prefer Swift's way.

**Comment by claudepache** [comment]
That will be separate proposal. If you are interested, please follow https://github.com/gisenberg/proposal-nullary-coalescing
