### ISSUE TITLE
(a.b.c)?.d  - Would it support? 

### ISSUE THREAD

**Issue by mc-zone** [claudepache/es-optional-chaining#11]
Would it support ?

``` (a.b.c)?.d ```

It means: 

```a?.b?.c?.d```

**Comment by nhz-io** [comment]
Nope

**Comment by davidyaha** [comment]
`(a.b.c)?.d`
AFAIK it will be similar to
`a.b.c?.d`

**Comment by nhz-io** [comment]
yeah, exactly like that, otherwise its too ambiguous how you unwrap the parens

**Comment by claudepache** [comment]
> `(a.b.c)?.d`
> AFAIK it will be similar to
> `a.b.c?.d`

Exactly. Closing this issue.
