### ISSUE TITLE
Use null instead of undefined

### ISSUE THREAD

**Issue by Alxandr** [claudepache/es-optional-chaining#12]
Could we get the following to return `null` instead of `undefined`?

```js
const a = null;
return a?.b;
```

I'm not saying that `null` on LHS => `null` on RHS, I'd just prefer `null` on RHS in general, regardless of `null` or `undefined` on LHS. `null` is shorter to type and is a language keyword as opposed to `undefined`. It would also make it easier to distinguish properties that are not defined such as this:

```js
const a = { foo: 5 };
const b = null;
const c = void 0;

a?.foo; // 5
a?.bar; // undefined

b?.foo; // null
b?.bar; // null

c?.foo; // null
c?.bar; // null
```

**Comment by RangerMauve** [comment]
I think the reason undefined was used instead of null is that that is the value that's returned when one accesses an undefined property. I'd say that staying consistent with other language features is more important, though doing comparisons with `null` would be more ergonomic

**Comment by claudepache** [comment]
Repeating what I've said in https://github.com/claudepache/es-optional-chaining/issues/8#issuecomment-275190327

> Neither `a.b` nor `a?.b` is intended to preserve arbitrary information on the base object `a`, but only to give information about the property `"b"` of that object. If a property `"b"` is absent from `a`, this is reflected by `a.b === undefined`.
> 
> In the particular case, `null` and `undefined` are both treated as immutable ”objects” with no properties. Therefore, we have `a?.b === undefined` for both `a === null` and `a === undefined`, because the property `"b"` is absent from both `null` and `undefined`.

Given that this question was raised more than once, I'll write it down explicitly as part of the justification of the semantics. Noted in #8.

**Comment by Alxandr** [comment]
I'd still like to argue the fact that we didn't lookup `b` on `null` (in your quoted text), because given that `a` is `null` or `undefined` no lookup happens at all. Therefore, the end result of the expression `a?.b` is in my opinion totally up in the air and to be defined by the operator itself because it's not the same as looking up `b` on `null` (which is not at all undefined, but a `TypeError`). My point is that this is new behaviour that is to be defined, and defining it as `null` would be the better choice in my opinion.

**Comment by hax** [comment]
@Alxandr 
```js
var a = {}
a?.bar // undefined

a?.bar.foo // null or undefined?
```

**Comment by Alxandr** [comment]
@hax last one is a typeerror, no? Cause it looks up `bar` on `a` (cause a exists), and the next one is not a "safe" lookup. Thus you get `no foo on undefined error`. Same as

```js
var a = {bar: null};
a?.bar; // null

a?.bar.foo; // TypeError: cannot lookup foo on null
a?.bar?.foo; // safe: with current proposal will be undefined, I think it should be null.

**Comment by nhz-io** [comment]
Null is a value. Undefined is undefined. Otherwise it ambiguous again, and non-intuitive.
It smells like **==** vs **===**

**Comment by Yogu** [comment]
I think always using `undefined` will cause unexpected problems with TypeScript when `...|null` is used:

    class Node {
        parentNode: Node|null = null;
    }

    const someNode = new Node();
    let node: Node|null = someNode.parentNode?.parentNode;

This will not compile as the null propagating operator will result in the type `Node|undefined` instead of `Node|null`. Of course, using `undefineed` like proposed here would just lead to the same problem with `Node|undefined`, and you have a valid point of why not to use `null` or `undefined` depending on the left hand side. So I don't have a solution, just want to point it out.
