### ISSUE TITLE
Clarification on ?.3

### ISSUE THREAD

**Issue by notoriousb1t** [claudepache/es-optional-chaining#14]
Firstly, excellent proposal!  Looking over the notes I see 

> In order to allow foo?.3:0 to be parsed as foo ? .3 : 0 rather than foo ?. 3 : 0, a simple lookahead is added at the level of the lexical grammar (the ?. token should not be followed by a decimal digit).

```foo.3``` isn't a valid property access in the first place.  I think this might be confusing.

**Comment by claudepache** [comment]
The lookahead restriction is not about avoiding to parse as `foo  ?.  3 : 0` (which would be invalid anyway even without the restriction), but it is about succeeding to parse as `foo  ?  .3 : 0`. Maybe the following formulation is clearer?:

> In order to allow `foo?.3:0` to be parsed as `foo ? .3 : 0` (as required for backward compatibility),  a simple lookahead is added at the level of the lexical grammar, so that the sequence of characters `?.` is not interpreted as a single token in that situation  (the `?.` token must not be immediately followed by a decimal digit).

**Comment by notoriousb1t** [comment]
That is much clearer. 👍
