### ISSUE TITLE
How will methods on number literals be handled?

### ISSUE THREAD

**Issue by Mouvedia** [claudepache/es-optional-chaining#15]
```
// equivalent of (1).toString()
1..toString();
1 .toString()

// is this valid?
1.?.mayNotExist;

// same question (mind the space)
1 ?.mayNotExist;

**Comment by hax** [comment]
`1 .toString()` is syntax error.

`1.?.mayNotExist` could be valid as my understanding. `1?.mayNotExist` could also be valid.
But when you write number literal, it seems no need to use optional chaining (you definitely know what prop/methods on number type), so another choice is disallow both (force you to write `(1)?.any` if you really want it).

**Comment by Mouvedia** [comment]
> `1 .toString()` is syntax error.

No it's not. Try it out.

> (you definitely know what prop/methods on number type)

True that; but we still need to cover both cases.

> another choice is disallow

That wouldn't be in line with other operators that were previously introduced. That's up to an ESLint rule to detect unneeded usage. 
For example I have one to detect this kind of cases: `[...[1]]`

**Comment by claudepache** [comment]
Both `1?.mayNotExist` and `1 ?.mayNotExist` will work as expected: there is nothing special here. The issue with `1.toString()` is that the dot is interpreted as part of the numeric literal (as a decimal point). That won’t happen if there is anything between the digit and the dot that can’t be part of a numeric literal.

**Comment by claudepache** [comment]
Also, yes, `1.?.mayNotExist` is valid: the first dot is part of a numeric literal.
