### ISSUE TITLE
Why not use the the common getIn pattern

### ISSUE THREAD

**Issue by jhicken** [claudepache/es-optional-chaining#17]
So I have 2 questions the first is the syntax change on this feel pretty different from what I am used to. I had to think about it a bit. 

1: So why not just use a getIn method on the Object prototype similar in syntax to what is done with immutable or lodash. 
```
let noodles = { flavorless: {round:  {}}}
noodles.getIn(['flavorless','round', 'purple']);
```
https://facebook.github.io/immutable-js/docs/#/Map/getIn

2: The second question is... Does this handle being a setter as well as a getter?

So could you do something like this?

`a?.c?.d = 'magic';`

If so does it return a new object?

**Comment by claudepache** [comment]
For the first question: The getIn pattern is interesting, but is limited to property lookup; I want also optional method calls, such as `foo?.bar()` and `foo.bar?.()`. I’ll write soon a few use cases for these forms. (Incidentally it is not a good idea to put that operator on `Object.prototype` for well understood reasons that I won’t develop here.)

For the second question: as currently specced, `a?.b = c` is equivalent to `a.b = c` if `a` is not null/undefined, and it does nothing if `a` is null/undefined. There is no “magic” creation of new object. Basically, the `?` means “the whole expression evaluates to nothing if what is on the left is null/undefined”.  However, whether this is useful (and therefore whether this should be allowed) when used as a setter is an open question.

**Comment by jhicken** [comment]
Cool thanks for the reply.

Okay so on the first part.

The argument to not modify Object.prototype is not really valid here. Since this would be a proposal to change what the prototype originally contains. Its very similar to what is currently done with something like Object.prototype.keys.

Im going to stray off subject here a little.

So if I understand correctly this is valid.
`a.b ?. () ?. c ?. stuff`

If a.b().c evaluates to be valid. During the evaluation b() is run twice? Is that correct.

Seems a little dangerous for multi run evaluation but that could just be well documented as a warning.

I would a think not doing 'magical' deep setting would be a good thing in this situation. 

The main reason I bring this up is that I am considering putting together a proposal for setIn and getIn. I wanted to know your compelling reasons for this approach instead.

**Comment by claudepache** [comment]
> So if I understand correctly this is valid.
> `a.b ?. () ?. c ?. stuff`
> 
> If a.b().c evaluates to be valid. During the evaluation b() is run twice? Is that correct.

No, there is never double execution of code. The whole expression is evaluated from left to right as usual. If what is at the left of `?` evaluates to null/undefined, the whole expression returns immediately undefined. Otherwise, evaluation proceeds normally, without recomputing what is already evaluated.

**Comment by jhicken** [comment]
Cool I think I understand all of this now. And I think this is sufficient to understand the difference between what a getIn would be. I will go ahead and close this for now.
