### ISSUE TITLE
Should grouping parentheses as in (a?.b) interrupt short-circuiting?

### ISSUE THREAD

**Issue by claudepache** [claudepache/es-optional-chaining#19]
That is, should

```js
(a?.b).c
```

be equivalent to 

(1) `(a == null ? undefined : a.b).c`

rather than 

(2) `a?.b.c`, or `(a == null ? undefined : a.b.c)` (as currently specced)?

As currently specced, grouping parentheses are transparent w.r.t. Nil references: this is consistent with how References work, but it is not necessarily a desirable consistency, as the Nil reference is a spec mechanism that the average user does not need to know.

One may rather want to make the semantics more similar to how short-circuiting or conditional evaluation works with other operators that have such a feature, namely `||`, `&&`, and `?  :`.

Any feedback is welcome. What is more intuitive, (1) or (2)?

**Comment by Mouvedia** [comment]
In that peculiar example I think that `(a?.b).c` and `a?.b.c` are equivalent.

> What is more intuitive, (1) or (2)?

2

**Comment by MaienM** [comment]
1

**Comment by saschanaz** [comment]
1 for me.

**Comment by Wedvich** [comment]
To me 1 is the most intuitive - I would expect it to work the same way as the other short-circuiting operators mentioned.

**Comment by claudepache** [comment]
I have chosen option 1.

**Comment by Mouvedia** [comment]
So you prefer to throw a TypeError over returning `undefined`. I wonder why would you do that example in the first place then.

**Comment by claudepache** [comment]
@Mouvedia Regardless of the semantics, there is hardly a practical reason to use parentheses in this situation anyway.
