### ISSUE TITLE
Optional call returns references

### ISSUE THREAD

**Issue by zenparsing** [claudepache/es-optional-chaining#4]
Previously EvaluateDirectCall would either throw or return an ECMAScript language value (i.e. not a Reference), but now it can return a NilReference.  And since PutValue is a no-op for NilReferences, it looks like this would be allowed:

``` js
let obj = {};
obj.foo?.() = 1;
```

Whereas I think we'd want a ReferenceError here.

**Comment by zenparsing** [comment]
Sorry, I messed up the example (I think the cascading behavior is confusing me).

``` js
let obj = {};
obj.foo?.() = 1;
```

(I'll fix the issue description as well.)

**Comment by nhz-io** [comment]
Assigning to rvalue allowed now?

**Comment by claudepache** [comment]
I haven’t yet much explored the use cases for PutValue on a Nil Reference. One could indeed throw an error instead of doing nothing, in case one thinks that it is a better semantic.

**Comment by claudepache** [comment]
Those forms are removed. They will throw the same error as `obj.foo() = 1`.
