### ISSUE TITLE
Working with es6 const, let

### ISSUE THREAD

**Issue by a-x-** [claudepache/es-optional-chaining#5]
is there definition for the case:

`const {fooBar} = res?.data?.buisnessData // equals const fooBar = _.get(res, 'data.buisnessData.fooBar')`

**Comment by claudepache** [comment]
@a-x- const/let and destructuring is orthogonal to optional chaining. <del>In particular, `const {fooBar} = anything` is always equivalent to: `const fooBar = anything.fooBar`.</del> Nothing new.

I don’t know what you mean by  `_.get(...)`.

**Comment by a-x-** [comment]
`_` is the `lodash`:
https://lodash.com/docs#get

**Comment by a-x-** [comment]
thank you

**Comment by claudepache** [comment]
In reality, as currently specced, `const {fooBar} = <anything>` is not equivalent to:

``` js
const fooBar = <anything>.fooBar
```

but to:

``` js
const tmp = <anything>
const fooBar = tmp.fooBar
```

which makes a difference when `<anything>` is an expression containing an optional chaining operator; see #7.
