### ISSUE TITLE
Interaction with destructuring assignment

### ISSUE THREAD

**Issue by claudepache** [claudepache/es-optional-chaining#7]
For example, what should  the following code do:

``` js
({ c } = a?.b)
```

As currently specced:

``` js
let tmp = a?.b
c = tmp.c // will throw if `a` is undefined/null
```

Another possible semantics:

``` js
c = a?.b.c  // will put `undefined` in `c` if `a` is undefined/null
```

If we choose the latter (well, even if we don’t), we should also consider if we need a syntax for expressing:

``` js
c = d?.c
```

e.g.

``` js
({ c } = d?.)
({ ?.c } = d)
```

**Comment by a-x-** [comment]
i propose unary `?.` operator:

let's consider example:

`const { c } = ?.a?.b`

`if (typeof window.hasOwnKey(a) == false) c === undefined` // no throwing exceptions
`if (typeof window.hasOwnKey(a) == true && !a.b) c === undefined` // a defined, but has no key `b`

**Comment by borela** [comment]
It would make more sense for it to never throw and prevent unnecessary `try catch`.

**Comment by claudepache** [comment]
For the sake of simplicity, the “stupid” semantics won’t be modified. The reason is that I don’t want to add more complicate semantics than the relatively simple short-circuiting. In case that there are sufficiently strong interest that justify a more complicated semantics, that could be changed “later” (as it is generally safe to change from throwing to not throwing), or an alternative solution may.
