### ISSUE TITLE
Null conditional operator

### ISSUE THREAD

**Issue by artemgurzhii** [claudepache/es-optional-chaining#9]
As for now, I  can see that it can only return `undefined` in case variable is `undefined/null`.
In C# 6 was introducet `null conditional operator` which can return value if second case is executed.
```C#
int count = people?.Length ?? 0;
```
Equivalent in javascript
```javascript
let count = people ? people.length : 0;
```
Also, I didn't find explanation if it is going to work this way
```javascript
let q = p?.x?.y;
```
same as
```javascript
let q = (p === undefined) ? undefined : (p.x === undefined) ? undefined : p.x.y;
```
or same code in more convenient way
```javascript
let q;
if (p !== undefined) {
  if (p.x !== undefined) {
    q = p.x.y;
  }
}
```
Some relates links [first](http://www.informit.com/articles/article.aspx?p=2421572), [second](https://blogs.msdn.microsoft.com/csharpfaq/2014/11/20/new-features-in-c-6/).

**Comment by claudepache** [comment]
`?.` is what they call the null-conditional operator, and is exactly the subject of this repository.

`??` is the null-coalescing operator (https://msdn.microsoft.com/en-us/magazine/ms173224(vs.90).aspx). It is a somewhat related nice-to-have operator, but is out of the scope of this proposal.

**Comment by artemgurzhii** [comment]
But what about returned value? In this case
```C#
int count = people?.Length ?? 0;
```
if `people` is not defined, returned value is `0`.
```javascript
let count = people?.length;
```
But here, if `people` is not defined, returned value is `undefined` and can't be configured.

**Comment by RangerMauve** [comment]
@artemgurzhii Until a null-coalescing operator proposal is introduced you can have `let count = people?.length || 0`

**Comment by claudepache** [comment]
@artemgurzhii I’ve taken note of the demand for `??` in Issue #10.
